export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function ManualLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children; // Just return children, no HTML/body tags
}
